registros = [
    {
        "cidade": "Atlanta",
        "grupo": {"Andrew", "Abigail", "Charlotte", "Elizabeth", "Penelope", "Emily"},
        "duracao": 28,
        "transacoes": [
            ("480.93", "cartao"),
            ("955.71", "cartao"),
            ("1485.00", "dinheiro"),
            ("436.63", "dinheiro"),
            ("1353.80", "dinheiro"),
            ("518.86", "cartao"),
            ("1244.36", "cartao"),
            ("1643.67", "dinheiro"),
            ("231.25", "cartao"),
            ("995.24", "cartao"),
            ("959.98", "dinheiro"),
            ("1716.91", "dinheiro"),
        ],
    },
    {
        "cidade": "Los Angeles",
        "grupo": {"Lily", "Emily", "Scarlett"},
        "duracao": 22,
        "transacoes": [
            ("1305.81", "cartao"),
            ("493.75", "dinheiro"),
            ("1177.65", "cartao"),
            ("701.38", "cartao"),
            ("1558.88", "dinheiro"),
            ("171.09", "dinheiro"),
            ("1313.51", "dinheiro"),
            ("421.61", "cartao"),
        ],
    },
    {
        "cidade": "Houston",
        "grupo": {"Amelia", "Zoe", "Sophia", "Harper"},
        "duracao": 22,
        "transacoes": [
            ("315.48", "cartao"),
            ("185.13", "dinheiro"),
            ("1916.79", "dinheiro"),
            ("669.02", "dinheiro"),
            ("1670.53", "cartao"),
        ],
    },
    {
        "cidade": "Miami",
        "grupo": {"Alexander", "Henry", "Sophia", "Harper", "Andrew"},
        "duracao": 25,
        "transacoes": [
            ("1562.58", "dinheiro"),
            ("614.78", "dinheiro"),
            ("907.37", "cartao"),
        ],
    },
    {
        "cidade": "Denver",
        "grupo": {
            "Lucas",
            "Olivia",
            "Penelope",
            "Victoria",
            "James",
            "Chloe",
            "Samuel",
            "Emily",
        },
        "duracao": 23,
        "transacoes": [
            ("215.05", "dinheiro"),
            ("166.03", "cartao"),
            ("851.05", "dinheiro"),
            ("1258.88", "cartao"),
            ("1298.00", "cartao"),
        ],
    },
    {
        "cidade": "Boston",
        "grupo": {"Elijah", "Victoria"},
        "duracao": 26,
        "transacoes": [
            ("379.59", "cartao"),
            ("808.74", "cartao"),
            ("1596.04", "cartao"),
            ("65.32", "cartao"),
            ("975.32", "cartao"),
            ("1223.46", "dinheiro"),
            ("781.96", "dinheiro"),
        ],
    },
    {
        "cidade": "Houston",
        "grupo": {
            "William",
            "Lucas",
            "Henry",
            "Elizabeth",
            "Benjamin",
            "Zoe",
            "Andrew",
            "Madison",
        },
        "duracao": 15,
        "transacoes": [
            ("1730.03", "dinheiro"),
            ("1688.66", "dinheiro"),
            ("579.59", "dinheiro"),
            ("25.73", "cartao"),
            ("692.24", "cartao"),
            ("247.86", "cartao"),
            ("1093.16", "dinheiro"),
            ("1527.26", "dinheiro"),
            ("1654.52", "dinheiro"),
            ("413.20", "cartao"),
            ("716.68", "cartao"),
        ],
    },
    {
        "cidade": "Las Vegas",
        "grupo": {"Lily", "Noah", "Ava", "Grace", "Ella", "Aiden"},
        "duracao": 17,
        "transacoes": [],
    },
    {
        "cidade": "Las Vegas",
        "grupo": {"Lily", "Alexander", "James", "Ella", "Joseph", "Zoe", "Michael"},
        "duracao": 14,
        "transacoes": [
            ("327.16", "cartao"),
            ("557.26", "dinheiro"),
            ("1834.48", "dinheiro"),
        ],
    },
    {
        "cidade": "Miami",
        "grupo": {"Lucas", "Samuel"},
        "duracao": 14,
        "transacoes": [
            ("1028.94", "dinheiro"),
            ("1102.93", "cartao"),
            ("187.31", "dinheiro"),
            ("1741.73", "cartao"),
            ("1664.90", "dinheiro"),
            ("376.57", "dinheiro"),
            ("591.13", "dinheiro"),
            ("1932.09", "cartao"),
            ("1054.29", "cartao"),
        ],
    },
    {
        "cidade": "Seattle",
        "grupo": {"William", "Matthew", "Mason", "Daniel", "Ava", "Liam", "Madison"},
        "duracao": 11,
        "transacoes": [
            ("1746.73", "cartao"),
            ("1951.48", "dinheiro"),
            ("1298.15", "cartao"),
        ],
    },
    {
        "cidade": "New York",
        "grupo": {"Elizabeth", "Christopher", "Isabella", "Michael"},
        "duracao": 28,
        "transacoes": [
            ("1516.33", "dinheiro"),
            ("1504.43", "dinheiro"),
            ("136.98", "dinheiro"),
            ("982.43", "cartao"),
            ("1428.40", "dinheiro"),
            ("60.12", "cartao"),
            ("1866.56", "dinheiro"),
            ("1790.93", "dinheiro"),
            ("1388.53", "dinheiro"),
            ("1371.68", "dinheiro"),
            ("628.95", "cartao"),
            ("1113.53", "cartao"),
        ],
    },
    {
        "cidade": "Atlanta",
        "grupo": {"William", "Lily", "Daniel", "Ethan", "Andrew", "Aiden"},
        "duracao": 19,
        "transacoes": [
            ("1735.77", "dinheiro"),
            ("445.07", "cartao"),
            ("656.27", "cartao"),
            ("389.89", "dinheiro"),
            ("1733.42", "dinheiro"),
            ("1358.75", "dinheiro"),
            ("1602.64", "dinheiro"),
            ("1598.66", "cartao"),
            ("1644.55", "cartao"),
            ("759.75", "dinheiro"),
        ],
    },
    {
        "cidade": "New York",
        "grupo": {"Daniel", "Andrew", "Victoria", "Chloe"},
        "duracao": 20,
        "transacoes": [
            ("824.75", "cartao"),
            ("1215.67", "dinheiro"),
            ("1665.60", "dinheiro"),
            ("517.92", "cartao"),
            ("1852.32", "cartao"),
        ],
    },
    {
        "cidade": "Seattle",
        "grupo": {
            "Amelia",
            "Christopher",
            "Henry",
            "Elizabeth",
            "Grace",
            "Mia",
            "Sophia",
        },
        "duracao": 8,
        "transacoes": [
            ("1671.12", "dinheiro"),
            ("1948.92", "dinheiro"),
            ("770.73", "cartao"),
            ("132.08", "cartao"),
            ("916.16", "cartao"),
        ],
    },
    {
        "cidade": "Dallas",
        "grupo": {"Lucas", "Isabella"},
        "duracao": 4,
        "transacoes": [],
    },
    {
        "cidade": "Miami",
        "grupo": {"Mason", "Ethan", "James", "Victoria", "Scarlett", "Samuel"},
        "duracao": 24,
        "transacoes": [
            ("600.23", "cartao"),
            ("609.88", "cartao"),
            ("166.49", "dinheiro"),
            ("1059.43", "dinheiro"),
        ],
    },
    {
        "cidade": "Las Vegas",
        "grupo": {"Lily", "Ava", "James", "Grace", "Samuel"},
        "duracao": 28,
        "transacoes": [
            ("1218.63", "cartao"),
            ("1858.54", "dinheiro"),
            ("1163.16", "dinheiro"),
            ("1590.90", "cartao"),
        ],
    },
    {
        "cidade": "San Francisco",
        "grupo": {"Daniel", "Ella", "David", "Scarlett"},
        "duracao": 28,
        "transacoes": [
            ("1112.65", "cartao"),
            ("1800.05", "dinheiro"),
            ("221.31", "cartao"),
            ("1012.01", "cartao"),
            ("478.02", "cartao"),
            ("991.85", "cartao"),
            ("39.46", "cartao"),
            ("469.00", "cartao"),
            ("1183.95", "dinheiro"),
            ("1012.24", "dinheiro"),
        ],
    },
    {
        "cidade": "Las Vegas",
        "grupo": {
            "Mason",
            "Matthew",
            "Henry",
            "James",
            "Penelope",
            "Chloe",
            "Isabella",
        },
        "duracao": 22,
        "transacoes": [
            ("1634.23", "cartao"),
            ("249.10", "cartao"),
            ("1311.72", "dinheiro"),
            ("1481.48", "dinheiro"),
            ("1863.22", "dinheiro"),
            ("1769.30", "dinheiro"),
        ],
    },
    {
        "cidade": "Houston",
        "grupo": {"Lucas", "Michael"},
        "duracao": 11,
        "transacoes": [("11.13", "cartao")],
    },
    {
        "cidade": "Chicago",
        "grupo": {"Ava", "Liam"},
        "duracao": 12,
        "transacoes": [
            ("1608.82", "dinheiro"),
            ("1997.51", "dinheiro"),
            ("1122.35", "cartao"),
        ],
    },
    {
        "cidade": "Chicago",
        "grupo": {"Lucas", "Emily", "Mason"},
        "duracao": 18,
        "transacoes": [
            ("165.36", "dinheiro"),
            ("1043.01", "cartao"),
            ("1251.35", "cartao"),
            ("1134.70", "cartao"),
        ],
    },
    {
        "cidade": "Dallas",
        "grupo": {"Alexander", "James", "Chloe", "Liam", "Sophia", "Samuel", "Andrew"},
        "duracao": 30,
        "transacoes": [("967.18", "dinheiro")],
    },
    {
        "cidade": "Miami",
        "grupo": {"Elijah", "Christopher", "Victoria"},
        "duracao": 17,
        "transacoes": [("6.96", "cartao")],
    },
    {
        "cidade": "New York",
        "grupo": {
            "Lucas",
            "Abigail",
            "Alexander",
            "Elizabeth",
            "Victoria",
            "Ella",
            "David",
            "Samuel",
        },
        "duracao": 29,
        "transacoes": [
            ("126.03", "dinheiro"),
            ("1568.29", "cartao"),
            ("1339.05", "dinheiro"),
            ("1638.29", "dinheiro"),
            ("1941.21", "cartao"),
            ("52.52", "cartao"),
            ("241.60", "cartao"),
        ],
    },
    {
        "cidade": "Houston",
        "grupo": {"Lucas", "Benjamin", "Charlotte"},
        "duracao": 17,
        "transacoes": [
            ("1251.78", "cartao"),
            ("443.40", "cartao"),
            ("494.12", "dinheiro"),
            ("645.54", "cartao"),
            ("1286.65", "dinheiro"),
            ("1457.16", "dinheiro"),
            ("613.53", "cartao"),
            ("1497.67", "cartao"),
            ("398.91", "dinheiro"),
            ("31.20", "cartao"),
            ("378.78", "cartao"),
            ("1858.64", "cartao"),
            ("267.48", "dinheiro"),
        ],
    },
    {
        "cidade": "Atlanta",
        "grupo": {"Lucas", "Ethan", "Zoe"},
        "duracao": 7,
        "transacoes": [
            ("383.58", "dinheiro"),
            ("1992.04", "cartao"),
            ("1136.71", "dinheiro"),
            ("748.65", "cartao"),
            ("1723.67", "cartao"),
            ("1239.64", "cartao"),
        ],
    },
    {
        "cidade": "Houston",
        "grupo": {
            "Abigail",
            "Alexander",
            "Victoria",
            "Zoe",
            "Harper",
            "Samuel",
            "Michael",
        },
        "duracao": 11,
        "transacoes": [
            ("320.26", "dinheiro"),
            ("1329.88", "cartao"),
            ("1163.19", "cartao"),
            ("1288.24", "cartao"),
            ("1024.45", "cartao"),
            ("489.29", "dinheiro"),
            ("925.37", "cartao"),
            ("486.07", "cartao"),
            ("1705.04", "cartao"),
            ("1459.39", "dinheiro"),
            ("313.15", "cartao"),
            ("34.49", "cartao"),
            ("1005.74", "dinheiro"),
            ("258.72", "cartao"),
            ("98.65", "dinheiro"),
        ],
    },
    {
        "cidade": "Atlanta",
        "grupo": {"Madison", "Harper", "Mason", "Charlotte"},
        "duracao": 30,
        "transacoes": [
            ("1483.09", "dinheiro"),
            ("1700.05", "dinheiro"),
            ("1861.77", "dinheiro"),
            ("1692.09", "cartao"),
            ("616.96", "cartao"),
            ("1510.13", "cartao"),
            ("1022.70", "dinheiro"),
            ("743.36", "dinheiro"),
            ("1873.16", "dinheiro"),
            ("1597.18", "dinheiro"),
            ("649.04", "cartao"),
            ("993.51", "dinheiro"),
            ("923.78", "dinheiro"),
            ("1622.43", "dinheiro"),
            ("771.62", "dinheiro"),
        ],
    },
    {
        "cidade": "Chicago",
        "grupo": {
            "Lucas",
            "Abigail",
            "Elizabeth",
            "Olivia",
            "Harper",
            "David",
            "Madison",
        },
        "duracao": 26,
        "transacoes": [
            ("865.14", "cartao"),
            ("1980.22", "cartao"),
            ("1881.23", "dinheiro"),
            ("1605.40", "cartao"),
            ("777.94", "dinheiro"),
        ],
    },
    {
        "cidade": "San Francisco",
        "grupo": {"Matthew", "Christopher", "Olivia", "Ella", "Joseph", "Harper"},
        "duracao": 8,
        "transacoes": [("611.54", "cartao")],
    },
    {
        "cidade": "Boston",
        "grupo": {"Joseph", "Chloe"},
        "duracao": 9,
        "transacoes": [
            ("49.26", "cartao"),
            ("502.07", "dinheiro"),
            ("261.33", "cartao"),
            ("1928.74", "cartao"),
            ("544.12", "dinheiro"),
            ("927.37", "cartao"),
            ("333.06", "dinheiro"),
            ("1822.12", "cartao"),
        ],
    },
    {
        "cidade": "Boston",
        "grupo": {"Liam", "Christopher", "Madison"},
        "duracao": 7,
        "transacoes": [
            ("1205.11", "cartao"),
            ("735.29", "dinheiro"),
            ("1133.55", "cartao"),
            ("1126.43", "dinheiro"),
            ("1186.16", "cartao"),
            ("667.05", "cartao"),
            ("1825.84", "cartao"),
            ("1747.78", "dinheiro"),
            ("136.88", "cartao"),
            ("1476.95", "dinheiro"),
            ("1353.86", "cartao"),
            ("245.75", "dinheiro"),
            ("659.79", "cartao"),
            ("813.02", "cartao"),
        ],
    },
    {
        "cidade": "Atlanta",
        "grupo": {"Christopher", "Isabella"},
        "duracao": 4,
        "transacoes": [
            ("1289.79", "dinheiro"),
            ("902.35", "dinheiro"),
            ("1139.70", "cartao"),
            ("898.14", "dinheiro"),
            ("1821.00", "cartao"),
            ("684.09", "dinheiro"),
            ("579.99", "dinheiro"),
            ("115.07", "dinheiro"),
            ("43.96", "dinheiro"),
            ("1628.40", "cartao"),
            ("219.32", "cartao"),
            ("1564.49", "cartao"),
            ("1749.34", "cartao"),
            ("1304.86", "cartao"),
            ("1209.27", "cartao"),
            ("1867.38", "cartao"),
        ],
    },
    {
        "cidade": "Chicago",
        "grupo": {"Alexander", "Grace", "Chloe", "Joseph", "Samuel", "Michael"},
        "duracao": 30,
        "transacoes": [
            ("483.18", "dinheiro"),
            ("465.09", "cartao"),
            ("1809.64", "cartao"),
            ("304.48", "dinheiro"),
            ("486.37", "dinheiro"),
            ("371.76", "cartao"),
            ("731.18", "dinheiro"),
            ("431.66", "cartao"),
            ("1567.70", "dinheiro"),
            ("796.34", "cartao"),
            ("734.97", "cartao"),
            ("81.24", "dinheiro"),
            ("1936.22", "cartao"),
        ],
    },
    {
        "cidade": "Chicago",
        "grupo": {"William", "Olivia", "David", "Michael"},
        "duracao": 5,
        "transacoes": [
            ("1652.51", "dinheiro"),
            ("1751.16", "cartao"),
            ("1102.36", "cartao"),
        ],
    },
    {
        "cidade": "Seattle",
        "grupo": {"Christopher", "James", "Isabella", "Joseph", "Harper", "Samuel"},
        "duracao": 21,
        "transacoes": [
            ("1278.24", "cartao"),
            ("1335.96", "dinheiro"),
            ("838.83", "cartao"),
            ("978.87", "cartao"),
            ("1143.55", "cartao"),
            ("356.00", "dinheiro"),
        ],
    },
    {
        "cidade": "Boston",
        "grupo": {"Ava", "Victoria"},
        "duracao": 26,
        "transacoes": [
            ("1922.40", "dinheiro"),
            ("526.52", "dinheiro"),
            ("1841.72", "dinheiro"),
            ("851.57", "cartao"),
            ("446.64", "cartao"),
        ],
    },
    {
        "cidade": "Dallas",
        "grupo": {"Noah", "Ethan", "Liam", "Harper", "Scarlett", "Andrew"},
        "duracao": 24,
        "transacoes": [
            ("124.95", "cartao"),
            ("628.09", "dinheiro"),
            ("1149.21", "cartao"),
            ("1893.37", "cartao"),
            ("20.41", "dinheiro"),
        ],
    },
    {
        "cidade": "Miami",
        "grupo": {
            "Mason",
            "Ava",
            "Ethan",
            "James",
            "Grace",
            "Sophia",
            "Harper",
            "Madison",
        },
        "duracao": 14,
        "transacoes": [
            ("1507.67", "dinheiro"),
            ("694.24", "cartao"),
            ("790.48", "cartao"),
            ("1912.99", "cartao"),
            ("544.89", "cartao"),
            ("907.54", "dinheiro"),
            ("1815.15", "cartao"),
            ("1805.25", "dinheiro"),
            ("358.36", "cartao"),
            ("480.52", "dinheiro"),
            ("717.28", "dinheiro"),
            ("405.64", "cartao"),
        ],
    },
    {
        "cidade": "Denver",
        "grupo": {
            "Mason",
            "Daniel",
            "Ava",
            "James",
            "Ella",
            "Joseph",
            "Harper",
            "Michael",
        },
        "duracao": 3,
        "transacoes": [
            ("76.31", "cartao"),
            ("241.67", "dinheiro"),
            ("140.10", "dinheiro"),
            ("375.15", "cartao"),
            ("206.42", "cartao"),
            ("938.06", "cartao"),
        ],
    },
    {
        "cidade": "Los Angeles",
        "grupo": {"Amelia", "Mason", "Daniel", "Ethan", "Isabella", "Joseph"},
        "duracao": 11,
        "transacoes": [("1180.39", "dinheiro"), ("1426.05", "dinheiro")],
    },
    {
        "cidade": "Las Vegas",
        "grupo": {
            "Mason",
            "Lucas",
            "Elizabeth",
            "James",
            "Chloe",
            "Ella",
            "Zoe",
            "Liam",
        },
        "duracao": 14,
        "transacoes": [
            ("1995.94", "cartao"),
            ("1031.59", "dinheiro"),
            ("1430.94", "cartao"),
            ("274.48", "dinheiro"),
            ("23.23", "cartao"),
            ("108.32", "dinheiro"),
            ("1357.04", "cartao"),
            ("523.36", "cartao"),
            ("156.23", "dinheiro"),
            ("910.14", "cartao"),
            ("1837.76", "dinheiro"),
        ],
    },
    {
        "cidade": "New York",
        "grupo": {
            "Lily",
            "Amelia",
            "Lucas",
            "Mason",
            "Victoria",
            "Isabella",
            "Joseph",
            "Zoe",
        },
        "duracao": 19,
        "transacoes": [
            ("355.79", "dinheiro"),
            ("1849.02", "cartao"),
            ("1593.42", "cartao"),
            ("1813.09", "cartao"),
            ("1062.93", "cartao"),
            ("1407.52", "cartao"),
            ("1398.93", "cartao"),
            ("732.29", "dinheiro"),
        ],
    },
    {
        "cidade": "Dallas",
        "grupo": {"Lily", "Ava", "Elizabeth", "James", "Aiden"},
        "duracao": 3,
        "transacoes": [
            ("633.24", "dinheiro"),
            ("604.86", "cartao"),
            ("622.54", "cartao"),
            ("792.46", "cartao"),
            ("1707.47", "cartao"),
            ("1384.08", "cartao"),
            ("1643.59", "dinheiro"),
        ],
    },
    {
        "cidade": "Seattle",
        "grupo": {"Matthew", "Mason", "Henry", "Daniel", "Ethan", "Mia", "Aiden"},
        "duracao": 22,
        "transacoes": [
            ("1840.14", "dinheiro"),
            ("17.18", "cartao"),
            ("538.20", "dinheiro"),
            ("1336.12", "cartao"),
            ("414.30", "dinheiro"),
            ("1884.49", "dinheiro"),
            ("1953.92", "cartao"),
            ("738.08", "dinheiro"),
        ],
    },
    {
        "cidade": "Los Angeles",
        "grupo": {"Ava", "Joseph", "Benjamin", "Penelope"},
        "duracao": 10,
        "transacoes": [
            ("886.67", "cartao"),
            ("842.18", "dinheiro"),
            ("781.05", "cartao"),
            ("948.60", "dinheiro"),
            ("1285.73", "cartao"),
            ("1889.42", "cartao"),
            ("115.24", "dinheiro"),
            ("1917.35", "cartao"),
            ("1107.86", "dinheiro"),
            ("177.62", "cartao"),
            ("1810.58", "cartao"),
            ("1158.24", "cartao"),
            ("1625.42", "cartao"),
            ("615.93", "dinheiro"),
        ],
    },
    {
        "cidade": "Seattle",
        "grupo": {"Amelia", "Matthew", "Ava", "Elizabeth", "Michael"},
        "duracao": 17,
        "transacoes": [],
    },
    {
        "cidade": "Los Angeles",
        "grupo": {"Scarlett", "Abigail", "Aiden", "Chloe"},
        "duracao": 15,
        "transacoes": [("711.08", "dinheiro"), ("572.23", "dinheiro")],
    },
    {
        "cidade": "Denver",
        "grupo": {
            "William",
            "Ethan",
            "Benjamin",
            "Penelope",
            "Mia",
            "Liam",
            "Scarlett",
            "Emily",
        },
        "duracao": 23,
        "transacoes": [
            ("7.36", "cartao"),
            ("1811.01", "cartao"),
            ("675.40", "cartao"),
            ("1933.56", "cartao"),
            ("1432.95", "cartao"),
            ("11.57", "dinheiro"),
            ("1243.82", "dinheiro"),
            ("390.10", "dinheiro"),
        ],
    },
    {
        "cidade": "New York",
        "grupo": {"William", "Elizabeth", "Ethan", "Benjamin", "Victoria", "Emily"},
        "duracao": 11,
        "transacoes": [
            ("861.81", "cartao"),
            ("421.01", "dinheiro"),
            ("1869.77", "cartao"),
            ("1946.83", "cartao"),
            ("294.44", "cartao"),
            ("1475.90", "cartao"),
            ("585.12", "cartao"),
        ],
    },
    {
        "cidade": "Houston",
        "grupo": {
            "Amelia",
            "Henry",
            "Elizabeth",
            "Isabella",
            "Chloe",
            "Ella",
            "Harper",
            "Michael",
        },
        "duracao": 26,
        "transacoes": [("1323.64", "dinheiro"), ("7.79", "cartao")],
    },
    {
        "cidade": "New York",
        "grupo": {"Penelope", "Victoria"},
        "duracao": 16,
        "transacoes": [
            ("469.26", "dinheiro"),
            ("1559.23", "dinheiro"),
            ("1115.85", "dinheiro"),
            ("868.44", "dinheiro"),
            ("222.46", "dinheiro"),
            ("1361.53", "dinheiro"),
            ("462.39", "dinheiro"),
            ("414.86", "cartao"),
            ("1924.96", "cartao"),
            ("810.01", "dinheiro"),
            ("1901.61", "cartao"),
            ("1860.87", "cartao"),
            ("864.41", "dinheiro"),
        ],
    },
    {
        "cidade": "Atlanta",
        "grupo": {"Mason", "Christopher", "Ava", "Scarlett", "David"},
        "duracao": 7,
        "transacoes": [
            ("969.03", "dinheiro"),
            ("1358.23", "dinheiro"),
            ("1501.81", "dinheiro"),
            ("1240.91", "cartao"),
            ("531.30", "cartao"),
            ("1626.04", "dinheiro"),
        ],
    },
    {
        "cidade": "New York",
        "grupo": {"Ava", "Lily"},
        "duracao": 30,
        "transacoes": [
            ("719.90", "dinheiro"),
            ("488.88", "dinheiro"),
            ("1774.38", "dinheiro"),
            ("1188.02", "dinheiro"),
            ("481.02", "cartao"),
            ("1711.24", "cartao"),
            ("1450.17", "cartao"),
            ("1736.84", "dinheiro"),
            ("1802.41", "dinheiro"),
            ("838.89", "dinheiro"),
        ],
    },
    {
        "cidade": "Atlanta",
        "grupo": {"Matthew", "Noah", "Daniel", "Joseph", "Zoe"},
        "duracao": 23,
        "transacoes": [],
    },
    {
        "cidade": "Boston",
        "grupo": {"William", "Charlotte", "Victoria", "Zoe", "Michael", "Aiden"},
        "duracao": 19,
        "transacoes": [
            ("281.27", "cartao"),
            ("1527.74", "cartao"),
            ("1436.08", "cartao"),
            ("315.62", "cartao"),
            ("1674.55", "cartao"),
            ("83.55", "cartao"),
            ("927.40", "cartao"),
            ("568.64", "cartao"),
            ("383.12", "cartao"),
            ("552.55", "dinheiro"),
        ],
    },
    {
        "cidade": "Boston",
        "grupo": {"Andrew", "Liam", "Christopher", "Ella"},
        "duracao": 19,
        "transacoes": [],
    },
    {
        "cidade": "Chicago",
        "grupo": {"Isabella", "Zoe", "Harper", "Samuel", "Michael", "Aiden"},
        "duracao": 30,
        "transacoes": [],
    },
    {
        "cidade": "Boston",
        "grupo": {"Amelia", "Abigail", "Mason", "Charlotte", "Ava", "Liam"},
        "duracao": 9,
        "transacoes": [
            ("777.60", "cartao"),
            ("593.98", "cartao"),
            ("1781.70", "cartao"),
            ("1384.37", "cartao"),
        ],
    },
    {
        "cidade": "Chicago",
        "grupo": {"Mason", "Henry", "Ethan", "Olivia", "Victoria"},
        "duracao": 23,
        "transacoes": [
            ("1607.04", "cartao"),
            ("1988.11", "dinheiro"),
            ("201.05", "dinheiro"),
            ("491.05", "cartao"),
            ("1524.45", "cartao"),
            ("1901.05", "dinheiro"),
            ("1516.19", "dinheiro"),
            ("1450.91", "cartao"),
            ("912.21", "cartao"),
            ("930.10", "cartao"),
            ("1897.12", "dinheiro"),
            ("1991.25", "cartao"),
        ],
    },
    {
        "cidade": "Miami",
        "grupo": {
            "Amelia",
            "Matthew",
            "Charlotte",
            "Elizabeth",
            "Sophia",
            "David",
            "Michael",
        },
        "duracao": 19,
        "transacoes": [
            ("727.07", "dinheiro"),
            ("1456.35", "cartao"),
            ("333.83", "cartao"),
            ("405.93", "cartao"),
        ],
    },
    {
        "cidade": "Houston",
        "grupo": {"Amelia", "Liam", "Elizabeth"},
        "duracao": 16,
        "transacoes": [
            ("817.40", "dinheiro"),
            ("1467.58", "cartao"),
            ("1360.54", "dinheiro"),
            ("1359.80", "cartao"),
            ("1665.02", "cartao"),
            ("1167.86", "cartao"),
            ("911.87", "cartao"),
            ("1571.45", "cartao"),
            ("1655.67", "cartao"),
            ("1457.88", "dinheiro"),
            ("1345.63", "dinheiro"),
            ("1725.68", "dinheiro"),
        ],
    },
    {
        "cidade": "Dallas",
        "grupo": {"Christopher", "Henry", "Elizabeth", "James", "Scarlett"},
        "duracao": 16,
        "transacoes": [("379.86", "dinheiro")],
    },
    {
        "cidade": "Los Angeles",
        "grupo": {"Scarlett", "Sophia", "Noah"},
        "duracao": 7,
        "transacoes": [],
    },
    {
        "cidade": "Dallas",
        "grupo": {"Amelia", "Olivia", "Benjamin", "Scarlett", "Emily", "Andrew"},
        "duracao": 20,
        "transacoes": [
            ("1611.27", "cartao"),
            ("459.80", "cartao"),
            ("1004.87", "dinheiro"),
        ],
    },
    {
        "cidade": "Atlanta",
        "grupo": {"Henry", "Elizabeth", "Ava", "David", "Madison"},
        "duracao": 25,
        "transacoes": [
            ("583.33", "dinheiro"),
            ("726.17", "dinheiro"),
            ("511.39", "cartao"),
            ("1618.38", "dinheiro"),
            ("1052.39", "cartao"),
            ("618.30", "cartao"),
            ("1061.07", "dinheiro"),
            ("1123.70", "cartao"),
            ("1647.92", "dinheiro"),
            ("1518.66", "cartao"),
            ("1787.69", "cartao"),
        ],
    },
    {
        "cidade": "Atlanta",
        "grupo": {"Daniel", "Olivia", "Benjamin", "Zoe", "Emily", "Andrew"},
        "duracao": 13,
        "transacoes": [("705.76", "cartao"), ("1049.01", "dinheiro")],
    },
    {
        "cidade": "Houston",
        "grupo": {"Amelia", "Andrew", "Penelope", "Chloe"},
        "duracao": 9,
        "transacoes": [
            ("923.14", "cartao"),
            ("1826.02", "cartao"),
            ("1212.34", "cartao"),
            ("1021.81", "dinheiro"),
            ("814.02", "cartao"),
            ("88.82", "dinheiro"),
            ("1207.07", "dinheiro"),
            ("940.67", "cartao"),
            ("1746.90", "cartao"),
            ("1212.09", "cartao"),
            ("77.83", "cartao"),
            ("1852.36", "cartao"),
            ("1555.06", "dinheiro"),
            ("1185.61", "dinheiro"),
            ("997.93", "cartao"),
            ("1149.36", "dinheiro"),
        ],
    },
    {
        "cidade": "Chicago",
        "grupo": {"Matthew", "Lily", "Andrew"},
        "duracao": 21,
        "transacoes": [
            ("1780.72", "cartao"),
            ("1924.38", "cartao"),
            ("919.82", "cartao"),
            ("1163.98", "dinheiro"),
            ("910.36", "dinheiro"),
            ("225.91", "dinheiro"),
            ("205.13", "cartao"),
            ("726.90", "cartao"),
            ("1050.16", "cartao"),
        ],
    },
    {
        "cidade": "Boston",
        "grupo": {"Charlotte", "Ava", "Penelope", "Chloe", "David", "Elijah"},
        "duracao": 3,
        "transacoes": [
            ("1839.94", "cartao"),
            ("1289.21", "dinheiro"),
            ("1037.75", "cartao"),
            ("251.19", "dinheiro"),
            ("287.00", "cartao"),
            ("901.82", "cartao"),
            ("190.88", "dinheiro"),
            ("1847.70", "dinheiro"),
            ("1129.29", "cartao"),
            ("1712.87", "dinheiro"),
            ("979.66", "dinheiro"),
        ],
    },
    {
        "cidade": "Houston",
        "grupo": {"Daniel", "Amelia", "Alexander", "Charlotte"},
        "duracao": 18,
        "transacoes": [],
    },
    {
        "cidade": "Houston",
        "grupo": {"David", "Victoria"},
        "duracao": 5,
        "transacoes": [("1181.05", "cartao"), ("1217.69", "dinheiro")],
    },
    {
        "cidade": "Las Vegas",
        "grupo": {"Abigail", "Henry", "Noah", "Daniel", "Ava", "Grace"},
        "duracao": 22,
        "transacoes": [
            ("499.21", "dinheiro"),
            ("1650.21", "dinheiro"),
            ("1337.67", "cartao"),
            ("70.39", "cartao"),
            ("687.61", "dinheiro"),
            ("1663.66", "dinheiro"),
            ("1042.97", "dinheiro"),
            ("1515.11", "cartao"),
            ("1845.78", "cartao"),
            ("103.64", "cartao"),
            ("57.28", "dinheiro"),
            ("1464.09", "cartao"),
            ("1486.36", "cartao"),
        ],
    },
    {
        "cidade": "Miami",
        "grupo": {
            "Abigail",
            "Alexander",
            "Ava",
            "James",
            "Penelope",
            "Joseph",
            "Scarlett",
            "Emily",
        },
        "duracao": 26,
        "transacoes": [
            ("503.44", "cartao"),
            ("943.44", "cartao"),
            ("257.22", "dinheiro"),
            ("277.74", "cartao"),
            ("228.82", "dinheiro"),
            ("1564.66", "dinheiro"),
            ("626.34", "cartao"),
            ("1767.85", "dinheiro"),
        ],
    },
    {
        "cidade": "Denver",
        "grupo": {"Amelia", "Sophia", "Michael", "Aiden"},
        "duracao": 21,
        "transacoes": [
            ("1217.03", "cartao"),
            ("544.66", "cartao"),
            ("1328.42", "cartao"),
            ("1954.13", "cartao"),
            ("1961.14", "dinheiro"),
            ("1351.37", "dinheiro"),
            ("1248.36", "dinheiro"),
            ("34.70", "cartao"),
            ("347.32", "cartao"),
            ("85.82", "dinheiro"),
            ("563.45", "cartao"),
            ("420.54", "cartao"),
            ("1872.15", "dinheiro"),
        ],
    },
    {
        "cidade": "Boston",
        "grupo": {"Alexander", "Christopher", "Henry", "Grace", "Ella"},
        "duracao": 27,
        "transacoes": [
            ("434.38", "cartao"),
            ("464.93", "dinheiro"),
            ("377.37", "dinheiro"),
            ("816.22", "cartao"),
            ("1197.49", "cartao"),
            ("81.54", "dinheiro"),
            ("1287.87", "dinheiro"),
            ("1013.86", "cartao"),
            ("1345.10", "dinheiro"),
            ("1583.25", "dinheiro"),
            ("1409.94", "cartao"),
            ("1139.93", "dinheiro"),
            ("733.82", "cartao"),
            ("1346.93", "dinheiro"),
            ("85.26", "dinheiro"),
        ],
    },
    {
        "cidade": "Dallas",
        "grupo": {"Lily", "Daniel", "Isabella", "Mia", "Emily", "Madison"},
        "duracao": 8,
        "transacoes": [
            ("6.54", "cartao"),
            ("584.19", "cartao"),
            ("557.40", "dinheiro"),
            ("1858.13", "cartao"),
            ("117.66", "dinheiro"),
            ("1185.64", "cartao"),
            ("853.89", "dinheiro"),
            ("52.03", "dinheiro"),
            ("288.73", "cartao"),
            ("560.08", "cartao"),
            ("713.24", "cartao"),
            ("173.34", "dinheiro"),
            ("303.54", "dinheiro"),
            ("1804.23", "cartao"),
            ("23.83", "dinheiro"),
        ],
    },
    {
        "cidade": "Chicago",
        "grupo": {
            "Lucas",
            "Alexander",
            "Henry",
            "Ethan",
            "Liam",
            "Elijah",
            "Emily",
            "Michael",
        },
        "duracao": 29,
        "transacoes": [
            ("150.88", "dinheiro"),
            ("607.50", "cartao"),
            ("1425.27", "dinheiro"),
            ("1021.90", "dinheiro"),
            ("431.03", "dinheiro"),
            ("1346.66", "dinheiro"),
            ("269.83", "dinheiro"),
            ("169.66", "dinheiro"),
            ("1884.02", "cartao"),
            ("887.39", "cartao"),
            ("12.09", "cartao"),
        ],
    },
    {
        "cidade": "Boston",
        "grupo": {"Alexander", "Elizabeth", "Victoria", "Chloe", "Emily"},
        "duracao": 21,
        "transacoes": [("911.64", "cartao")],
    },
    {
        "cidade": "Seattle",
        "grupo": {
            "William",
            "Lily",
            "Abigail",
            "Matthew",
            "Elizabeth",
            "Olivia",
            "Mia",
            "Michael",
        },
        "duracao": 22,
        "transacoes": [
            ("516.79", "dinheiro"),
            ("1019.28", "dinheiro"),
            ("1948.72", "cartao"),
            ("1940.65", "cartao"),
            ("1697.97", "cartao"),
            ("1621.38", "dinheiro"),
            ("1221.60", "cartao"),
            ("990.81", "cartao"),
            ("1581.24", "cartao"),
            ("1808.92", "dinheiro"),
            ("381.78", "cartao"),
            ("150.73", "dinheiro"),
            ("848.65", "dinheiro"),
        ],
    },
    {
        "cidade": "Las Vegas",
        "grupo": {
            "Amelia",
            "Olivia",
            "Penelope",
            "James",
            "Chloe",
            "Ella",
            "Liam",
            "David",
        },
        "duracao": 18,
        "transacoes": [("409.35", "dinheiro")],
    },
    {
        "cidade": "Miami",
        "grupo": {"Charlotte", "Ethan", "Penelope", "Chloe", "Ella", "Harper"},
        "duracao": 9,
        "transacoes": [
            ("1940.92", "cartao"),
            ("1176.24", "dinheiro"),
            ("1017.86", "cartao"),
            ("1152.61", "dinheiro"),
            ("795.03", "cartao"),
            ("1807.09", "cartao"),
            ("1957.94", "cartao"),
            ("870.42", "cartao"),
        ],
    },
    {
        "cidade": "Las Vegas",
        "grupo": {"Lucas", "Lily", "Olivia", "Harper", "David", "Andrew"},
        "duracao": 19,
        "transacoes": [
            ("1730.53", "dinheiro"),
            ("823.25", "dinheiro"),
            ("1000.76", "cartao"),
            ("814.29", "cartao"),
            ("1402.86", "dinheiro"),
            ("121.87", "cartao"),
            ("1095.40", "cartao"),
            ("293.83", "cartao"),
            ("1064.77", "dinheiro"),
            ("1274.38", "dinheiro"),
            ("166.67", "dinheiro"),
            ("1279.41", "dinheiro"),
            ("1647.44", "dinheiro"),
        ],
    },
    {
        "cidade": "Miami",
        "grupo": {"Zoe", "Victoria"},
        "duracao": 23,
        "transacoes": [
            ("1489.62", "dinheiro"),
            ("496.01", "dinheiro"),
            ("361.19", "cartao"),
            ("529.98", "dinheiro"),
        ],
    },
    {
        "cidade": "Boston",
        "grupo": {"Ava", "Liam", "Henry", "Ella"},
        "duracao": 29,
        "transacoes": [
            ("1396.71", "dinheiro"),
            ("384.75", "cartao"),
            ("580.64", "cartao"),
            ("918.63", "dinheiro"),
            ("1495.12", "cartao"),
            ("102.74", "dinheiro"),
        ],
    },
    {
        "cidade": "Houston",
        "grupo": {"Andrew", "Lily", "Christopher", "Grace"},
        "duracao": 11,
        "transacoes": [
            ("1951.47", "dinheiro"),
            ("1408.86", "dinheiro"),
            ("1418.16", "cartao"),
            ("1098.85", "cartao"),
            ("755.27", "dinheiro"),
            ("673.59", "dinheiro"),
            ("722.76", "dinheiro"),
            ("835.58", "dinheiro"),
            ("1474.28", "cartao"),
            ("693.14", "dinheiro"),
            ("474.76", "cartao"),
            ("1652.62", "cartao"),
            ("1617.48", "dinheiro"),
        ],
    },
    {
        "cidade": "Las Vegas",
        "grupo": {"James", "Michael"},
        "duracao": 12,
        "transacoes": [
            ("628.19", "cartao"),
            ("623.22", "dinheiro"),
            ("794.84", "dinheiro"),
            ("801.55", "dinheiro"),
            ("512.04", "dinheiro"),
            ("1783.36", "dinheiro"),
            ("669.02", "dinheiro"),
            ("871.42", "cartao"),
            ("1285.79", "dinheiro"),
            ("1034.38", "cartao"),
            ("848.65", "dinheiro"),
        ],
    },
    {
        "cidade": "Boston",
        "grupo": {"Amelia", "Joseph", "Zoe", "Charlotte"},
        "duracao": 29,
        "transacoes": [
            ("1570.62", "dinheiro"),
            ("1117.80", "cartao"),
            ("916.26", "cartao"),
            ("971.30", "dinheiro"),
            ("1186.51", "dinheiro"),
            ("456.18", "dinheiro"),
            ("344.65", "dinheiro"),
            ("1078.78", "cartao"),
            ("765.79", "dinheiro"),
        ],
    },
    {
        "cidade": "Houston",
        "grupo": {"Benjamin", "Chloe", "Mia", "Liam", "Andrew", "Michael"},
        "duracao": 11,
        "transacoes": [
            ("127.56", "cartao"),
            ("1911.12", "cartao"),
            ("1257.87", "dinheiro"),
            ("1083.03", "cartao"),
            ("1614.54", "dinheiro"),
            ("1140.89", "dinheiro"),
            ("1944.46", "cartao"),
            ("515.70", "cartao"),
            ("1436.76", "dinheiro"),
            ("980.02", "dinheiro"),
        ],
    },
    {
        "cidade": "Chicago",
        "grupo": {"Alexander", "Madison"},
        "duracao": 13,
        "transacoes": [
            ("1029.29", "cartao"),
            ("1198.28", "dinheiro"),
            ("537.40", "cartao"),
            ("1808.28", "cartao"),
            ("567.95", "cartao"),
            ("1219.90", "cartao"),
            ("1448.00", "dinheiro"),
            ("1064.30", "cartao"),
            ("1599.46", "dinheiro"),
        ],
    },
    {
        "cidade": "Atlanta",
        "grupo": {"Lucas", "Abigail", "Matthew", "Ava", "Ella", "Scarlett"},
        "duracao": 3,
        "transacoes": [
            ("1610.76", "dinheiro"),
            ("146.59", "cartao"),
            ("1750.69", "cartao"),
        ],
    },
    {
        "cidade": "Miami",
        "grupo": {
            "Mason",
            "Christopher",
            "Henry",
            "James",
            "Penelope",
            "Scarlett",
            "Aiden",
        },
        "duracao": 12,
        "transacoes": [
            ("249.12", "dinheiro"),
            ("19.11", "cartao"),
            ("1147.32", "cartao"),
            ("582.26", "dinheiro"),
            ("1544.10", "cartao"),
            ("1520.28", "dinheiro"),
            ("1718.27", "dinheiro"),
            ("516.22", "dinheiro"),
            ("1552.08", "dinheiro"),
            ("1829.87", "cartao"),
        ],
    },
    {
        "cidade": "New York",
        "grupo": {"Charlotte", "Chloe", "Mia", "Joseph", "Aiden"},
        "duracao": 16,
        "transacoes": [
            ("485.88", "dinheiro"),
            ("1529.73", "cartao"),
            ("686.48", "cartao"),
            ("1457.64", "cartao"),
            ("1498.86", "dinheiro"),
            ("1693.73", "dinheiro"),
            ("1444.87", "cartao"),
            ("415.83", "cartao"),
            ("1234.60", "cartao"),
            ("1447.90", "cartao"),
            ("203.49", "cartao"),
            ("629.44", "cartao"),
        ],
    },
    {
        "cidade": "New York",
        "grupo": {"Mason", "Ethan", "Scarlett"},
        "duracao": 26,
        "transacoes": [
            ("1750.58", "dinheiro"),
            ("1864.44", "dinheiro"),
            ("1883.59", "cartao"),
            ("1460.33", "dinheiro"),
            ("142.11", "dinheiro"),
            ("1321.77", "dinheiro"),
        ],
    },
    {
        "cidade": "Seattle",
        "grupo": {
            "Lucas",
            "Abigail",
            "Olivia",
            "Victoria",
            "Ella",
            "Samuel",
            "Michael",
            "Aiden",
        },
        "duracao": 8,
        "transacoes": [
            ("1006.35", "cartao"),
            ("1668.85", "cartao"),
            ("963.80", "dinheiro"),
            ("383.94", "dinheiro"),
            ("867.42", "cartao"),
            ("172.89", "dinheiro"),
            ("163.17", "cartao"),
            ("1522.72", "cartao"),
            ("418.59", "dinheiro"),
        ],
    },
    {
        "cidade": "Miami",
        "grupo": {"Benjamin", "Lucas", "Emily"},
        "duracao": 19,
        "transacoes": [
            ("1013.50", "cartao"),
            ("879.59", "dinheiro"),
            ("609.47", "cartao"),
            ("841.85", "cartao"),
            ("293.66", "cartao"),
            ("1863.04", "dinheiro"),
            ("1847.22", "cartao"),
            ("1185.93", "cartao"),
        ],
    },
    {
        "cidade": "Denver",
        "grupo": {"Lily", "Harper", "Aiden"},
        "duracao": 3,
        "transacoes": [
            ("1621.74", "dinheiro"),
            ("155.15", "dinheiro"),
            ("566.35", "dinheiro"),
            ("204.52", "cartao"),
            ("555.24", "cartao"),
            ("712.57", "dinheiro"),
            ("1787.18", "dinheiro"),
            ("279.93", "dinheiro"),
            ("106.79", "cartao"),
            ("1341.80", "dinheiro"),
            ("155.75", "cartao"),
            ("1910.07", "cartao"),
        ],
    },
    {
        "cidade": "Boston",
        "grupo": {"Christopher", "Victoria", "Harper", "Scarlett", "Elijah", "Madison"},
        "duracao": 8,
        "transacoes": [
            ("6.79", "dinheiro"),
            ("687.46", "dinheiro"),
            ("694.71", "cartao"),
            ("417.33", "dinheiro"),
            ("402.64", "dinheiro"),
            ("1433.31", "dinheiro"),
            ("1649.82", "dinheiro"),
            ("1359.46", "dinheiro"),
            ("424.52", "cartao"),
            ("1226.41", "dinheiro"),
            ("448.20", "dinheiro"),
            ("938.98", "cartao"),
            ("35.34", "cartao"),
            ("1398.96", "cartao"),
            ("241.28", "cartao"),
        ],
    }
]